// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onwbydtzjkvgwffharmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ud2J5ZHR6amt2Z3dmZmhhcm1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MzQwMTQsImV4cCI6MjA1NzIxMDAxNH0.L0nkDulOfhZ01_t-JQWhIjFrpFsJ4DS5WWPEqBAZPzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);